import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useState } from "react";
import {
  GetServerSideProps,
  GetServerSidePropsContext,
  PreviewData,
} from "next";
import withServerSideAuth from "@middleware/withServerSideAuth";
import { ParsedUrlQuery } from "querystring";

const inter = Inter({ subsets: ["latin"] });
const HomePage = () => {
  // const user = useUser();
  const [user, setUser] = useState({});

  return (
    <>
      <Head>
        <title>ChatForm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl font-bold text-red-800">
          ChatForm Landing Page
        </h1>
        <div>{JSON.stringify(user)}</div>
      </main>

      <footer></footer>
    </>
  );
};

export default HomePage;

// export const getServerSideProps: GetServerSideProps = async (
//   context: GetServerSidePropsContext<ParsedUrlQuery, PreviewData>
// ) => {
//   return await withServerSideAuth(context);
// };
